# Generated by Django 5.2.4 on 2025-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
