# Generated by Django 5.2.4 on 2025-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_remove_game_game_day_game_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(),
        ),
    ]
