# Generated by Django 5.2.4 on 2025-08-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_game_api_id_alter_game_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picks.week'),
        ),
    ]
