# Generated by Django 5.2.5 on 2025-08-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0005_alter_game_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='confidence_poitns',
            new_name='confidence_points',
        ),
    ]
