# Generated by Django 5.2.5 on 2025-08-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0006_rename_confidence_poitns_pick_confidence_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INPROGRESS', 'In Progress'), ('FINAL', 'Final'), ('POSTPONED', 'Postponed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20),
        ),
    ]
